# Generated by Django 4.2.7 on 2025-05-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_name',
            field=models.CharField(max_length=100, verbose_name='Tên ngân hàng'),
        ),
    ]
