# Generated by Django 4.2.7 on 2025-05-19 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_bankaccount_bank_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bankaccount',
            unique_together={('user', 'account_number', 'bank_name')},
        ),
    ]
